apiVersion: v1
kind: Service
metadata:
  name: k8s-main-service
  namespace: fiap-services
  labels:
    app: k8s-main-service
spec:
  type: ClusterIP
  selector:
    app: k8s-main-service
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
