# =============================================================================
# ServiceAccount - FIAP Tech Challenge API
# =============================================================================
# ServiceAccount com IRSA para acesso ao AWS Secrets Manager
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fiap-tech-challenge-api
  namespace: ftc-app
  labels:
    app.kubernetes.io/name: fiap-tech-challenge-api
    app.kubernetes.io/component: rbac
  annotations:
    # IRSA annotation - ARN da role sera preenchido via Kustomize overlay
    eks.amazonaws.com/role-arn: ""
